### ISSUE TITLE
it violates Content Security Policy on chrome

### ISSUE THREAD

**Issue by dong1lkim** [BesrourMS/story#1]
Hello, I'm newbie pico cms user.
I like your pico theme, story.

on IE, it works perfectly
but, on Chrome, it doesn't

Chrome developer tool said,
Refused to load the script 'https://<...>/apps/cms_pico/Pico/themes/story/js/jquery.min.js' because it violates the following Content Security Policy directive: "script-src 'nonce-Nm1Ma2ZvS1dqTTFLLzVOWEZHdE5aTWJxalhUc2E4RUc5MTEveHlRaFZlVT06Z0NhaVQ5dnZ2b1EvbHNrVUpnY21MZjdCenc2Z0JvSmxsQlFxcFcxQUJaVT0=' 'unsafe-eval'".

How can I fix it?
please tell me how to fix it.

I really want to use this theme on Chrome.

**Comment by BesrourMS** [comment]
Try to use jQuery via CDN
